name: Roku Card services
description: 📺 Roku Remote Card edited
type: lovelace
keywords:
  - rokued
  - remoteed
  - tved
  - televisioned
author:
  name: mar_robHD
license: Apache License, Version 2.0
files:
  - roku-card-edited.js
  - roku-card-edited-editor.js
